spring:
  datasource:
    #数据源基本配置



    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源的其他配置
    druid:
      username: sa
      password: 147258369zh
      driver-class-name: com.mysql.jdbc.Driver

      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port: 8081